# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cat_tree.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selTree(object):
    def setupUi(self, selTree):
        selTree.setObjectName("selTree")
        selTree.resize(308, 598)
        self.verticalLayout = QtWidgets.QVBoxLayout(selTree)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree_db = QtWidgets.QTreeView(selTree)
        self.tree_db.setObjectName("tree_db")
        self.verticalLayout.addWidget(self.tree_db)
        self.cancel_btn = QtWidgets.QPushButton(selTree)
        self.cancel_btn.setObjectName("cancel_btn")
        self.verticalLayout.addWidget(self.cancel_btn)

        self.retranslateUi(selTree)
        QtCore.QMetaObject.connectSlotsByName(selTree)

    def retranslateUi(self, selTree):
        _translate = QtCore.QCoreApplication.translate
        selTree.setWindowTitle(_translate("selTree", "Dialog"))
        self.cancel_btn.setText(_translate("selTree", "cancel"))
