# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plot_win(object):
    def setupUi(self, plot_win):
        plot_win.setObjectName("plot_win")
        plot_win.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(plot_win)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plot = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.plot.setObjectName("plot")
        self.horizontalLayout.addWidget(self.plot)
        plot_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(plot_win)
        QtCore.QMetaObject.connectSlotsByName(plot_win)

    def retranslateUi(self, plot_win):
        _translate = QtCore.QCoreApplication.translate
        plot_win.setWindowTitle(_translate("plot_win", "MainWindow"))
from PyQt5 import QtWebEngineWidgets
