# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'split.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_split(object):
    def setupUi(self, split):
        split.setObjectName("split")
        split.resize(368, 146)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(split)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.amount = QtWidgets.QLineEdit(split)
        self.amount.setObjectName("amount")
        self.horizontalLayout.addWidget(self.amount)
        self.period = QtWidgets.QComboBox(split)
        self.period.setCurrentText("")
        self.period.setObjectName("period")
        self.horizontalLayout.addWidget(self.period)
        self.category = QtWidgets.QComboBox(split)
        self.category.setObjectName("category")
        self.horizontalLayout.addWidget(self.category)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(split)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(split)
        self.buttonBox.accepted.connect(split.accept)
        self.buttonBox.rejected.connect(split.reject)
        QtCore.QMetaObject.connectSlotsByName(split)

    def retranslateUi(self, split):
        _translate = QtCore.QCoreApplication.translate
        split.setWindowTitle(_translate("split", "Dialog"))
