# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_statistics(object):
    def setupUi(self, statistics):
        statistics.setObjectName("statistics")
        statistics.resize(640, 395)
        self.verticalLayout = QtWidgets.QVBoxLayout(statistics)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bankList_combo = QtWidgets.QComboBox(statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.bankList_combo.sizePolicy().hasHeightForWidth())
        self.bankList_combo.setSizePolicy(sizePolicy)
        self.bankList_combo.setObjectName("bankList_combo")
        self.horizontalLayout.addWidget(self.bankList_combo)
        self.del_btn = QtWidgets.QPushButton(statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.del_btn.sizePolicy().hasHeightForWidth())
        self.del_btn.setSizePolicy(sizePolicy)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout.addWidget(self.del_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 180))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 624, 207))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statTab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.statTab.sizePolicy().hasHeightForWidth())
        self.statTab.setSizePolicy(sizePolicy)
        self.statTab.setMinimumSize(QtCore.QSize(0, 80))
        self.statTab.setObjectName("statTab")
        self.verticalLayout_2.addWidget(self.statTab)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.statPlot = QtWebEngineWidgets.QWebEngineView(statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.statPlot.sizePolicy().hasHeightForWidth())
        self.statPlot.setSizePolicy(sizePolicy)
        self.statPlot.setMinimumSize(QtCore.QSize(0, 100))
        self.statPlot.setObjectName("statPlot")
        self.verticalLayout.addWidget(self.statPlot)

        self.retranslateUi(statistics)
        QtCore.QMetaObject.connectSlotsByName(statistics)

    def retranslateUi(self, statistics):
        _translate = QtCore.QCoreApplication.translate
        statistics.setWindowTitle(_translate("statistics", "Dialog"))
        self.label.setText(_translate("statistics", "Select import:"))
        self.del_btn.setText(_translate("statistics", "remove selected import"))
        self.statTab.setText(_translate("statistics", "<html><head/><body><p>html table of imports</p></body></html>"))
from PyQt5 import QtWebEngineWidgets
