# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_2(object):
    def setupUi(self, import_2):
        import_2.setObjectName("import_2")
        import_2.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(import_2)
        self.buttonBox.setGeometry(QtCore.QRect(270, 240, 111, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(import_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 88, 34))
        self.pushButton.setObjectName("pushButton")
        self.listView = QtWidgets.QListView(import_2)
        self.listView.setGeometry(QtCore.QRect(240, 20, 131, 181))
        self.listView.setObjectName("listView")
        self.pushButton_2 = QtWidgets.QPushButton(import_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 88, 34))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(import_2)
        self.buttonBox.accepted.connect(import_2.accept)
        self.buttonBox.rejected.connect(import_2.reject)
        QtCore.QMetaObject.connectSlotsByName(import_2)

    def retranslateUi(self, import_2):
        _translate = QtCore.QCoreApplication.translate
        import_2.setWindowTitle(_translate("import_2", "import data"))
        self.pushButton.setText(_translate("import_2", "from file"))
        self.pushButton_2.setText(_translate("import_2", "PushButton"))
