# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_banking(object):
    def setupUi(self, banking):
        banking.setObjectName("banking")
        banking.resize(800, 600)
        banking.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(banking)
        self.centralwidget.setObjectName("centralwidget")
        self.tabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMenu.setGeometry(QtCore.QRect(10, 10, 461, 84))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMenu.sizePolicy().hasHeightForWidth())
        self.tabMenu.setSizePolicy(sizePolicy)
        self.tabMenu.setMaximumSize(QtCore.QSize(461, 331))
        self.tabMenu.setObjectName("tabMenu")
        self.data = QtWidgets.QWidget()
        self.data.setObjectName("data")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.data)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_DB = QtWidgets.QPushButton(self.data)
        self.open_DB.setObjectName("open_DB")
        self.horizontalLayout.addWidget(self.open_DB)
        self.new_DB = QtWidgets.QPushButton(self.data)
        self.new_DB.setObjectName("new_DB")
        self.horizontalLayout.addWidget(self.new_DB)
        self.save_DB = QtWidgets.QPushButton(self.data)
        self.save_DB.setObjectName("save_DB")
        self.horizontalLayout.addWidget(self.save_DB)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabMenu.addTab(self.data, "")
        self.wrangling = QtWidgets.QWidget()
        self.wrangling.setObjectName("wrangling")
        self.tabMenu.addTab(self.wrangling, "")
        self.cat = QtWidgets.QWidget()
        self.cat.setObjectName("cat")
        self.tabMenu.addTab(self.cat, "")
        self.finished = QtWidgets.QPushButton(self.centralwidget)
        self.finished.setGeometry(QtCore.QRect(700, 10, 88, 34))
        self.finished.setObjectName("finished")
        banking.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(banking)
        self.statusbar.setObjectName("statusbar")
        banking.setStatusBar(self.statusbar)
        self.actionopen_DB = QtWidgets.QAction(banking)
        self.actionopen_DB.setObjectName("actionopen_DB")
        self.actionnew_DB = QtWidgets.QAction(banking)
        self.actionnew_DB.setObjectName("actionnew_DB")
        self.actionimport_from_file = QtWidgets.QAction(banking)
        self.actionimport_from_file.setObjectName("actionimport_from_file")
        self.actionscratch_WEB = QtWidgets.QAction(banking)
        self.actionscratch_WEB.setObjectName("actionscratch_WEB")
        self.actionsave_DB = QtWidgets.QAction(banking)
        self.actionsave_DB.setObjectName("actionsave_DB")
        self.actionExit = QtWidgets.QAction(banking)
        self.actionExit.setObjectName("actionExit")
        self.actionhelp = QtWidgets.QAction(banking)
        self.actionhelp.setObjectName("actionhelp")
        self.actionoptions = QtWidgets.QAction(banking)
        self.actionoptions.setObjectName("actionoptions")

        self.retranslateUi(banking)
        self.tabMenu.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(banking)

    def retranslateUi(self, banking):
        _translate = QtCore.QCoreApplication.translate
        banking.setWindowTitle(_translate("banking", "MainWindow"))
        self.open_DB.setText(_translate("banking", "open DB"))
        self.new_DB.setText(_translate("banking", "new DB"))
        self.save_DB.setText(_translate("banking", "save DB"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.data), _translate("banking", "data"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.wrangling), _translate("banking", "wrangling"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.cat), _translate("banking", "categorize"))
        self.finished.setText(_translate("banking", "finished"))
        self.actionopen_DB.setText(_translate("banking", "open DB"))
        self.actionnew_DB.setText(_translate("banking", "new DB"))
        self.actionimport_from_file.setText(_translate("banking", "import from file"))
        self.actionscratch_WEB.setText(_translate("banking", "scratch WEB"))
        self.actionsave_DB.setText(_translate("banking", "save DB"))
        self.actionExit.setText(_translate("banking", "Exit"))
        self.actionhelp.setText(_translate("banking", "help"))
        self.actionoptions.setText(_translate("banking", "options"))
